const converter = () => {
  return [
    {
      type: "test",
      question:
        "¿Qué aspecto de la persona de Jesús enfatiza el evangelio de Lucas?",
      A: "El carisma de Jesús",
      B: "Los milagros que Jesús realizó",
      C: "Cristo como el salvador del hombre",
      D: "La Deidad de Cristo",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "¿Qué aspecto de la persona de Jesús enfatiza el evangelio Juan?",
      A: "Cristo como el Verbo de Dios",
      B: "Las obras de caridad de Jesús",
      C: "El linaje de Cristo desde Abraham",
      D: "Los milagros de Jesús",
      correcta: "A",
    },
    {
      type: "test",
      question:
        "¿Cuáles son los animales que simbolizan los cuatro evangelios en relación con la visión de Ezequiel, en orden( Mateo, Marcos,Lucas y Juan)?",
      A: "Buey, León, Hombre y Cordero",
      B: "Hombre, León, Buey y Águila",
      C: "Águila, Cordero, Buey y Hombre",
      D: "León, Águila, Hombre y buey",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Cuál es el libro más antiguo de la Biblia?",
      A: "Génesis",
      B: "Deuteronomio",
      C: "Job",
      D: "Proverbios",
      correcta: "C",
    },
    {
      type: "test",
      question: "¿Cuál de estas frases no es bíblica?",
      A: "Ámate a ti mismo.",
      B: "Ama a Dios por encima de todas las cosas.",
      C: "Toma tu cruz cada día y sígueme",
      D: "Perdona a tu hermano hasta 70 veces 7",
      correcta: "A",
    },
    {
      type: "test",
      question: "¿Cúal es la raíz de todos los males según la Biblia?",
      A: "El amar al prójimo",
      B: "La baja autoestima",
      C: "El amor al dinero",
      D: "Hacer caso a Satanás",
      correcta: "C",
    },
    {
      type: "test",
      question: "Dios nos ha dado un espíritu de...",
      A: "Fuego, gloria y poder.",
      B: "profecías, nuevas lenguas y amor.",
      C: "alabanza, dominio propio y valor.",
      D: "amor, poder y dominio propio.",
      correcta: "D",
    },
    {
      type: "test",
      question:
        'Al clamar "Dios mío, Dios mío, ¿Por qué me has abandonado?" en la cruz,Jesús está llevando a cumplimiento la profecía escrita en...',
      A: "Salmo 35",
      B: "Isaías 15",
      C: "Salmo 22",
      D: "Jeremías 28",
      correcta: "C",
    },
    {
      type: "test",
      question: "¿Cuál de estos NO es uno de los 10 mandamientos?",
      A: "Siempre darás limosna.",
      B: "No matarás.",
      C: "No te harás imágenes delante de mí.",
      D: "No codiciarás la mujer de tu prójimo.",
      correcta: "A",
    },
    {
      type: "test",
      question:
        "¿Cuál de estos NO es uno de los libertadores de Israel en el libro de Jueces?",
      A: "Sansón",
      B: "Jeroboam",
      C: "Aod",
      D: "Abdón",
      correcta: "B",
    },
    {
      type: "test",
      question:
        "Después de la separación, ¿Qué tribus formaban el reino de Judá?",
      A: "Judá y Zabulón",
      B: "Judá y Benjamín",
      C: "Judá y Efraín",
      D: "Judá y Neftalí",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Debido al pecado de qué reyes se dividió el reino de Israel?",
      A: "Roboán y Salomón",
      B: "Salomón y Abdías",
      C: "Salomón y David",
      D: "Roboán y Absalón",
      correcta: "A",
    },
    {
      type: "test",
      question: "¿Qué significa el nombre de Dios, YAHVÉ/JEHOVÁ?",
      A: "Todopoderoso",
      B: "Rey de reyes",
      C: "Yo Soy El Que Soy",
      D: "El Dios Que Provee",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "¿Qué personaje bíblico lucho contra Dios, y después de esto Dios le cambió el nombre y le convirtio en uno de los patriarcas de Su pueblo?",
      A: "Isaac",
      B: "Moisés",
      C: "Abraham",
      D: "Jacob",
      correcta: "D",
    },
    {
      type: "test",
      question: "¿Cuál de estas expresiones NO representa a Jesús?",
      A: "Hijo del hombre",
      B: "Profeta del señor",
      C: "Verbo de Dios",
      D: "Cordero de Dios",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Quién fué el escritor de la carta a los Hebreos?",
      A: "Pablo",
      B: "Pedro",
      C: "No se sabe con certeza, pero se piensa que fue Pablo",
      D: "No se sabe con certeza, pero se piensa que fue Pedro",
      correcta: "C",
    },
    {
      type: "test",
      question: "¿Quién fue el escritor de Apocalipsis?",
      A: "Juan",
      B: "Jacobo",
      C: "Pablo",
      D: "Pedro",
      correcta: "A",
    },
    {
      type: "test",
      question: "¿De quién NO fue descendiente Jesús?",
      A: "Rahab",
      B: "Booz",
      C: "Zorobabel",
      D: "Isacar",
      correcta: "D",
    },
    {
      type: "test",
      question: "¿Cuál de todas estas cosas aprendió Jesús?",
      A: "Obediencia",
      B: "Santidad",
      C: "Conocimiento",
      D: "Firmeza",
      correcta: "A",
    },
    {
      type: "test",
      question: "¿Qué fué lo primero que hizo Cristo después de ser bautizado?",
      A: "Predicar que el Reino de Dios se había acercado.",
      B: "Comenzar su ministerio sanando enfermos y obrando milagros.",
      C: "Ir al desierto a ser tentado por Satanás durante 40 días.",
      D: "Ir a buscar y llamar a sus primeros discípulos.",
      correcta: "C",
    },
    {
      type: "test",
      question: "¿En qué epoca vivió el profeta Zacarías?",
      A: "En el reino del norte, Israel.",
      B: "En el reino del sur, Judá.",
      C: "En la época del exilio en  Babilonia.",
      D: "En la época de la restauración del templo de Jerusalén.",
      correcta: "D",
    },
    {
      type: "test",
      question: "¿En cuántos días creó Dios el universo?",
      A: "3",
      B: "7",
      C: "6",
      D: "12",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "¿Quién fué el líder de Israel que hizo entrar al pueblo en la Tierra Prometida?",
      A: "Moisés",
      B: "Caleb",
      C: "Aarón",
      D: "Josué",
      correcta: "D",
    },
    {
      type: "test",
      question:
        "¿Cuántas vueltas tuvo que dar el pueblo de Israel a la ciudad de Jericó antes de conquistarla?",
      A: "7",
      B: "13",
      C: "14",
      D: "12",
      correcta: "B",
    },
    {
      type: "test",
      question:
        "¿Según el orden de quién es Jesucristo nuestro Sumo Sacerdote?",
      A: "Melquisedec",
      B: "Abraham",
      C: "Aarón",
      D: "Leví",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "¿Cuál es la reacción de Jonás cuando Dios lo envía a predicar arrepentimiento a Nínive?",
      A: "Toma un barco y huye en dirección a Tarsis.",
      B: "Toma un barco y huye en dirección a Jerusalén.",
      C: "Obedece y toma un barco hacia Nínive.",
      D: "Obedece y va caminando hacia Nínive.",
      correcta: "A",
    },
    {
      type: "test",
      question:
        '¿Cuántos guerreros componen el grupo de "los valientes de david"?',
      A: "40",
      B: "24",
      C: "60",
      D: "54",
      correcta: "D",
    },
    {
      type: "test",
      question:
        "¿Qué es lo que debemos hacer con la tentación según la Biblia?",
      A: "Enfrentarla.",
      B: "Huir de ella.",
      C: "Resistirla.",
      D: "Dominarla.",
      correcta: "B",
    },
    {
      type: "test",
      question:
        "¿Cuál es la primera respuesta de Isaías al ver la gloria de Dios en Isaías 6?",
      A: "Te doy toda la gloria, ¡oh, Padre Eterno!",
      B: "Heme aquí, envíame a mí.",
      C: "¡Ay de mí!, que soy hombre muerto.",
      D: "La virgen concebirá, y dará a luz a un nño, que tendrá por nombre Emanuel. ",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "¿Cuál era el oficio de David antes de ser ungido por Samuel como nuevo rey de Israel?",
      A: "Pastor de ovejas.",
      B: "Tañedor de arpa.",
      C: "Pastor de vacas.",
      D: "Agricultor.",
      correcta: "A",
    },
    {
      type: "test",
      question:
        "¿Cuál es el llamado de Jesús que tenemos que obedecer para entrar en el Reino de Dios?",
      A: "Creed y confiad.",
      B: "Arrepentíos y creed.",
      C: "Creed y perseverad.",
      D: "Arrepentíos y adorad.",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Qué dijo Jesús que debemos hacer los cristianos al ayunar?",
      A: "Dar muestras de arrepentimiento en público.",
      B: "Mostrar que estamos ayunando para que otros puedan ver nuestra devoción.",
      C: "Arreglarnos bien para que nadie note que estamos ayunando.",
      D: "Clamar a Dios y orar continuamente allí donde estemos para extender el evangelio.",
      correcta: "C",
    },
    {
      type: "test",
      question: "El cristianismo es...",
      A: "Un camino más para llegar a Dios",
      B: "El camino más seguro para ir al cielo.",
      C: "El único camino para tener una relación con Dios.",
      D: "Los principios y normas que nos ayudarán a ir al cielo.",
      correcta: "C",
    },
    {
      type: "test",
      question:
        "Hablando de la Biblia,¿Cuántos hombres inspirados por Dios la escribieron y a lo largo de cuántos años?",
      A: "40 hombres a lo largo de 1600 años.",
      B: "42 hombres a lo largo de 1200 años.",
      C: "40 hombres a lo largo de 1300 años.",
      D: "38 hombres a lo largo de 1600 años.",
      correcta: "A",
    },
    {
      type: "test",
      question: "¿Qué es necesario para ver el Reino de Dios?",
      A: "Dar frutos de arrepentimiento.",
      B: "Nacer de nuevo.",
      C: "Creer en Dios.",
      D: "Ser buena persona.",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Qué tres cosas permanecen, y cuál es la más importante?",
      A: "Fe, esperanza y amor. La fe.",
      B: "Fe, perserverancia y amor. El amor.",
      C: "Fe, confianza y gozo. La confianza.",
      D: "Fe, esperanza y amor. El amor.",
      correcta: "D",
    },
    {
      type: "test",
      question:
        "¿Cuántas copias de los manuscritos del Nuevo Testamento se conservan en la actualidad?",
      A: "2000 aprox.",
      B: "6000 aprox.",
      C: "3000 aprox.",
      D: "500 aprox.",
      correcta: "B",
    },
    {
      type: "test",
      question: "¿Qué hace Jesús con la Ley del Antiguo Testamento?",
      A: "La invalida.",
      B: "La cambia por la gracia.",
      C: "La lleva a su cumplimiento.",
      D: "La abroga.",
      correcta: "C",
    },
  ].map((q) => ({
    type: q.type,
    question: q.question,
    answers: [
      ["A", q.A, q.correcta === "A"],
      ["B", q.B, q.correcta === "B"],
      ["C", q.C, q.correcta === "C"],
      ["D", q.D, q.correcta === "D"],
    ],
  })); 
};

console.log(JSON.stringify(converter()));